//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartphonev3.Models
{
    using System;
    using System.Collections.Generic;
	public partial class GioHang
	{
        public int gio_hang_id { get; set; }
        public Nullable<int> khach_hang_id { get; set; }
        public Nullable<int> san_pham_id { get; set; }
        public int so_luong_san_pham { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual SanPham SanPham { get; set; }
		
	}
}
