//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartphonev3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinNguoiDung
    {
        public int nguoi_dung_id { get; set; }
        public string ten_day_du { get; set; }
        public string dia_chi { get; set; }
        public string so_dien_thoai { get; set; }
        public Nullable<System.DateTime> ngay_sinh { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
