//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartphonev3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public int thong_bao_id { get; set; }
        public Nullable<int> nguoi_dung_id { get; set; }
        public string noi_dung { get; set; }
        public System.DateTime ngay_gui { get; set; }
        public string trang_thai { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
